schema-version = "1.10.0"

[install]
nodejs.pkg-path = "nodejs"

jq.pkg-path = "jq"

git-crypt.pkg-path = "git-crypt"
fd.pkg-path = "fd"
beads.pkg-path = "beads"

[hook]
on-activate = '''
    _PI_ROOT="${FLOX_ENV_PROJECT:?flox not activated!}"

    # pi supports PI_CODING_AGENT_DIR but few extensions do, and the docs are
    # hard-coded. I'm just tired of fighting it.
    if [ "${_PI_ROOT}" != "${HOME}/.pi" ]; then
        echo "‼️ The project is checked out to ${_PI_ROOT}, it should be at ~/.pi"
        exit 1
    fi

    # do the base install
    [ -d "${_PI_ROOT}/node_modules" ] || ( cd "${_PI_ROOT}" && npm install )

    # do after setting any PI_CODING_* vars but before PI_OFFLINE
    if [ ! -e "${FLOX_ENV_CACHE}/pi-did-update-extensions" ]; then
        ${_PI_ROOT}/node_modules/.bin/pi update --extensions
        touch "${FLOX_ENV_CACHE}/pi-did-update-extensions"
    fi

    # disable all startup network operations described here, including update
    # checks, package update checks, and install/update telemetry.
    # export PI_OFFLINE=1

    export PATH="${FLOX_ENV_PROJECT}/bin:${PATH}"
'''

[options]
cuda-detection = false
